apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: behandler-elektronisk-kommunikasjon
  namespace: default
  labels:
    team: {{team}}
spec:
  image: "docker.pkg.github.com/navikt/behandler-elektronisk-kommunikasjon:{{tag}}"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  webproxy: true
  ingresses:
    - "https://behandler-elektronisk-kommunikasjon.nais.preprod.local"
  env:
    - name: CLIENT_ID
      value: c18eba24-f676-47db-9a97-3c66e9304aee
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/.well-known/openid-configuration
    - name: JWT_ISSUER
      value: https://sts.windows.net/966ac572-f5b7-4bbe-aa88-c76419c0f851/
    - name: SYFOSMMOTTAK_CLIENT_ID
      value: 589446d0-4e9d-41be-ae18-b6d001a8a328
    - name: DATABASE_URL
      value: jdbc:oracle:thin:@a01dbfl033.adeo.no:1521/emottak_q1
    - name: DATABASE_PREFIX
      value: emottak_q1